name: Price Check
on:
  schedule:
    - cron: '38 8 * * *' # Set this to your preferred UTC time
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          
      - name: Install & Run
        run: |
          pip install curl_cffi beautifulsoup4 python-dotenv
          python the_scraper.py

      - name: Run scraper
        env:
          api_key: ${{ secrets.api_key }}
          receiver_id: ${{ secrets.receiver_id }}
        run: python the_scraper.py
